=== romansokyrko/Epam_Tasks/xml/XMLExample/src/main/resources/deviceXSD.xsd
<?xml version="1.0"?>
<!DOCTYPE xml>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.example.com" xmlns="http://www.example.com"
	elementFormDefault="qualified">

	<xs:element name='devices'>
		<xs:complexType>
			<xs:sequence>
				<xs:element name='device' type='deviceType' minOccurs='0'
					maxOccurs='unbounded' />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="deviceType">
		<xs:all>
			<xs:element name="name" type="xs:string" />
			<xs:element name="origin" type="xs:string" />
			<xs:element name="price">
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:minInclusive value="0" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="type">
				<xs:complexType>
					<xs:all>
						<xs:element name="group" type="xs:string" />
						<xs:element name="peripheral" type="xs:boolean" />
						<xs:element name="energyConsumption" type="xs:integer" />
						<xs:element name="port" type="xs:string" minOccurs="0" />
					</xs:all>
				</xs:complexType>
			</xs:element>
		</xs:all>
		<xs:attribute name='critical' type='xs:boolean' />
	</xs:complexType>
</xs:schema>

=== romansokyrko/Epam_Tasks/xml/XMLExample/src/main/resources/device.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE xml>
<devices xmlns="http://www.example.com"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.example.com deviceXSD.xsd">
	<device critical="true">
		<type>
			<group>videocard</group>
			<peripheral>false</peripheral>
			<energyConsumption>90</energyConsumption>
		</type>
		<name>gtx 950</name>
		<origin>USA</origin>
		<price>3000</price>
	</device>
	<device critical="false">
		<type>
			<group>keyboard</group>
			<peripheral>true</peripheral>
			<energyConsumption>10</energyConsumption>
			<port>ps/2</port>
		</type>
		<name>steelseries 7g</name>
		<origin>USA</origin>
		<price>1000</price>
	</device>
	<device critical="true">
		<type>
			<group>processor</group>
			<peripheral>false</peripheral>
			<energyConsumption>13</energyConsumption>
		</type>
		<name>intel core i5</name>
		<origin>USA</origin>
		<price>3500</price>
	</device>
</devices>
